@startuml
'https://plantuml.com/state-diagram
[*] --> ChannelState

state ChannelState {
  [*] --> ChannelRegistered
  ChannelRegistered --> ChannelActive
  ChannelActive --> ChannelInactive
  ChannelInactive --> ChannelUnregistered
  ChannelUnregistered --> [*]
}
@enduml